### Récupérer toutes les guitares
GET http://localhost:3310/api/guitar
Content-Type: application/json

### Récupérer une guitare grâce à son Id
GET http://localhost:3310/api/guitar/1
Content-Type: application/json

### Ajouter une guitare avec le format json
POST http://localhost:3310/api/guitar
Content-Type: application/json

{
  "name": "Fender Stratocaster",
  "brand": "Fender",
  "price": 1200,
  "image": "https://example.com/stratocaster.jpg",
  "type": "Electric"
}

### Modifier un produit déjà existant
PUT http://localhost:3310/api/guitar/8
Content-Type: application/json

{
  "name": "ma guitare",
  "brand": "Martin",
  "price": 1500,
  "image": "https://www.music-privilege.fr/img/600/744/contains/catalog/product/g/m/gma-000x2e-01-b.jpg",
  "type": "Electro-Accoustic"
}

### Supprimer une guitare
DELETE http://localhost:3310/api/guitar/9